"""
Implement tests for the solver engine.

In this case, having the following function:

```
    f(x) = e^{-x^2}; [-1, 1]
```
We'll going to discretize the function into a set of variables, such as:

```
f(Var) = sum_i^N Var_i, where Var = e^{-x^2} and N = (1 - (-1)) / dx
```

For the Objective Function, we'll have the area of the revolution solid
produced by the previous function. In this case, the OB is:

```
    OB(Var) = 2*pi* [sum_i^N Var_i * np.sqrt( 1 + (dVar_i / di)^2 ) ]
```
"""
import numpy as np
# Local imports
from pymath_compute.solvers.opt_solver import OptSolver
from pymath_compute.methods import OptMethods
from pymath_compute import Variable


def f(x: float) -> float:
    """Function of initial values to generate the lower solid revolution
    
    This function is np.exp(-x**2)
    """
    return np.exp(- (x ** 2))


def objective_function(variables: list[Variable]) -> int | float:
    """Cost function. This represents the Area of the revolution solid
    generated by f(x).
    """
    # Get the sum of the values designed by the variables
    var_sum = sum(
        variable.value * np.sqrt(1 + variable.value ** 2)
        for variable in variables
    )
    # Then, calculate the area
    return 2 * np.pi * var_sum


if __name__ == "__main__":

    # ========================================== #
    #           VARIABLES DEFINITION             #
    # ========================================== #

    # Define the array of variables
    f_variables: list[Variable] = []
    # Define a x step value, and then, generate the entire number of
    # variables Var based on the N obtained
    X0 = -1
    XF = 1

    X_STEP = 0.001
    N_VARS = int(XF - X0 / X_STEP)
    X_LINSPACE = np.linspace(X0, XF, N_VARS)
    for i in range(N_VARS):
        # We do not define lb and ub so we can get the
        # default boundaries, being lb=-inf and ub=inf
        variable = Variable(name=f"Var_{i+1}")
        # Then, based on the function f(x) = e^{-x^2},
        # define the initial value of this variable
        variable.value = f(X_LINSPACE[i])
        # Append this variable
        f_variables.append(variable)

    # ========================================== #
    #             SOLVER DEFINITION              #
    # ========================================== #
    # Instance the solver
    solver = OptSolver()
    solver.set_variables(variables=f_variables)
    solver.set_objective_function(objective_function)
    # Set the parameters
    solver.set_solver_config({
        "solver_time": 30,
        "solver_method": OptMethods.GRADIENT_DESCENT
    })
    # Run the solver!
    solver.solve()
    # Evaluate the status
    print(f"The status is {solver.status}")
    # Generate a expression from the sum of variables
    expr = f_variables[0].to_expression()
    # print(f_variables[0])
    for var in f_variables[1:]:
        expr = expr + var
        # print(var)
    # Plot the solution
    expr.plot(
        # title="$f(x)$ revolution solid values with "+
        # f"A={round(objective_function(f_variables), 2)}",
        title="Valores de la curva del sólido de revolución " +
        f"de $f(x)$ con A={round(objective_function(f_variables), 2)}",
        xlabel="$Var_i$",
        # ylabel="$Var$ value",
        ylabel="Valor de $Var$",
        figsize=(10, 4),
        # store_as_pdf=True
    )
