name: Continuous Integration Workflow 👾

# Controls when the action will run. We only want that this action to happens when
# we open a pull request that points to main
on:
  pull_request:
    branches:
      - "main"

# ----------------------------------- #
#          DEFINE THE JOBS            #
# ----------------------------------- #

jobs:
  rust_ci:
    runs-on: ubuntu-latest
    name: Run Rust CI 🦀
    steps:
      - uses: ./.github/actions/rust_ci

  python_ci:
    runs-on: ubuntu-latest
    name: Run Python CI 🐍
    steps:
      - uses: ./.github/actions/python_ci

  tests_ci:
    runs-on: ubuntu-latest
    name: Run tests 🧪
    steps:
      - uses: ./.github/actions/tests_ci